name: {{name}}
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.3+1
  logger: ^2.3.0
  flutter_secure_storage: ^9.2.2
  gap: ^3.0.1
  curl_logger_dio_interceptor: ^1.0.0
  get_storage: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  extension_theme_generator: ^1.1.2

flutter:
  uses-material-design: true